import { hash, verify } from '@node-rs/argon2'
import { MIN_PASSWORD_LENGTH } from './constants.ts'

/**
 * `Algorithm.Argon2id` is an ambient const enum, which `isolatedModules`
 * forbids accessing — the transpiler compiles file by file and cannot see the
 * value. The number comes from the package itself (Argon2d=0, Argon2i=1,
 * Argon2id=2), checked on 2026-08-05, and the round-trip test in
 * `test/password.test.ts` breaks if it ever changes.
 */
const ARGON2ID = 2

/**
 * Password hashing with Argon2id.
 *
 * Parameters follow OWASP's first-choice recommendation for Argon2id (19 MiB of
 * memory, 2 iterations, parallelism 1). Memory is the cost that actually hurts
 * GPU attacks — raising iterations alone costs us and dedicated hardware the
 * same.
 *
 * The salt is generated by the library and travels inside the resulting hash,
 * so there is nothing to store in a separate column.
 */
const PARAMS = {
  algorithm: ARGON2ID,
  memoryCost: 19_456,
  timeCost: 2,
  parallelism: 1
} as const

export const MIN_LENGTH = MIN_PASSWORD_LENGTH

export function isTooShort (password: string): boolean {
  return password.length < MIN_LENGTH
}

export async function hashPassword (password: string): Promise<string> {
  if (isTooShort(password)) {
    throw new Error(`Password must be at least ${MIN_LENGTH} characters.`)
  }
  return await hash(password, PARAMS)
}

/**
 * Checks a password. Never throws — a malformed hash in the database returns
 * `false`.
 *
 * Letting the exception escape would turn one corrupt row into a 500 on the
 * sign-in screen, and the error message would tell the visitor that the email
 * exists.
 */
export async function verifyPassword (storedHash: string, password: string): Promise<boolean> {
  try {
    return await verify(storedHash, password, PARAMS)
  } catch {
    return false
  }
}

/**
 * Burns the same time a real check would, with no hash to check against.
 *
 * Without this, answering a non-existent email is instant while answering a
 * real one takes ~15 ms. That difference is measurable from outside and turns
 * the sign-in screen into an oracle for who has an account here — for a client
 * with 713k followers, that is not an academic concern.
 */
export async function burnEquivalentTime (): Promise<void> {
  await verifyPassword(THROWAWAY_HASH, 'password-that-will-not-match')
}

/* A real Argon2id hash of an irrelevant value, generated once with the PARAMS
   above. It has to be valid: a made-up hash makes `verifyPassword` fall into
   the catch in microseconds, and the timing equalisation would stop equalising
   exactly when it matters. Measured on 2026-08-05: ~15 ms, same as a real check. */
const THROWAWAY_HASH =
  '$argon2id$v=19$m=19456,t=2,p=1$W+R4mXCV7J9sPTK54xdyXg$' +
  'ym6TNuws7rA46tE7+tS1jVaT5OzLsLlPM6Frv8WU+/I'
